<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>devtools</AssemblyName>
    <RootNamespace>EmotePreviewer.DevTools</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EmotePreviewer.Core\EmotePreviewer.Core.csproj" />
    <ProjectReference Include="..\..\tests\EmotePreviewer.Fixtures\EmotePreviewer.Fixtures.csproj" />
  </ItemGroup>

</Project>
