<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\third_party\gta-toolkit\RageLib.GTA5\RageLib.GTA5.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLua" Version="1.7.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
